AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-first-repo
      ImageScanningConfiguration:
        ScanOnPush: true
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeBuildRole # Replace with your desired role name
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess # Grants full access to CodeBuild
        # - arn:aws:iam::aws:policy/AmazonS3FullAccess  # Grants full access to S3 (adjust as needed)
        # - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess  # Grants full access to CloudWatch Logs (adjust as needed)
        # Add other managed policies as needed for your CodeBuild project
#   MyCodeBuildProject:
#     Type: AWS::CodeBuild::Project
#     Properties:
#       Artifacts:
#         Type: CODEPIPELINE
#       Environment:
#         Type: LINUX_CONTAINER
#         ComputeType: BUILD_GENERAL1_SMALL
#         Image: aws/codebuild/standard:5.0
#       ServiceRole: !GetAtt CodeBuildRole.Arn
#       Source:
#         Type: GITHUB
#         Location: https://github.com/luis95garay/speech2text_sentimentanalysis.git
#       BuildSpec:
#         version: 0.2
#         phases:
#           build:
#             commands:
#               - docker build -t my-image .
#               - docker tag my-image:latest !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/my-first-repo:latest
# Outputs:
#   ImageArtifactLocation:
#     Value: !Sub s3://${MyCodeBuildProject.Artifacts.Location}
