AWSTemplateFormatVersion: "2010-09-09"
Description: My First stack
Parameters:
  InputBucketAudioPlayback:
    Type: String
    Default: playbackAudio
    Description: Folder that holds the audio files to playback in the browser.
  InputBucketFailedTranscriptions:
    Type: String
    Default: failedAudio
    Description: Folder that holds the audio files that for some reason failed transcription
  InputBucketName:
    Type: String
    Default: ""
    Description:
      (Optional) Existing bucket holding all audio files for the system.  Leave
      blank to automatically create new bucket with intelligent tiering storage and
      automated retention policy.
  InputBucketRawAudio:
    Type: String
    Default: originalAudio
    Description:
      Prefix/Folder that holds the audio files to be ingested into the
      system
  InputBucketOrigTranscripts:
    Type: String
    Default: originalTranscripts
    Description:
      "Folder that holds Transcripts from other applications (e.g. Live\
      \ Call Analytics) that are to be processed as if PCA had processed that audio\n"
  OutputBucketName:
    Type: String
    Default: ""
    Description:
      (Optional) Existing bucket where Transcribe output files are delivered.  Leave
      blank to automatically create new bucket with intelligent tiering storage and
      automated retention policy.
  OutputBucketTranscribeResults:
    Type: String
    Default: transcribeResults
    Description: Folder within the output S3 bucket where Transcribe results are written
  OutputBucketParsedResults:
    Type: String
    Default: parsedFiles
    Description: Folder within the output S3 bucket where parsed results are written
  RetentionDays:
    Type: Number
    Default: 365
    AllowedValues:
      - 30
      - 60
      - 90
      - 180
      - 365
      - 730
      - 1460
    Description:
      "When using auto-provisioned S3 buckets, your audio files and associated\
      \ call analysis data will be  automatically and permanently deleted after the\
      \ specified number of retention days. The application does not currently archive\
      \ recordings or call data.\n"
  Environment:
    Description:
      The type of environment to tag your infrastructure with. You can
      specify DEV (development), TEST (test), or PROD (production).
    Type: String
    AllowedValues:
      - DEV
      - TEST
      - PROD
    Default: PROD
  DatabaseName:
    Type: String
    Default: pca
    Description: Glue catalog database name used to contain tables/views for SQL integration.
Conditions:
  ShouldCreateInputBucket:
    Fn::Equals:
      - Ref: InputBucketName
      - ""
  ShouldCreateOutputBucket:
    Fn::Equals:
      - Ref: OutputBucketName
      - ""
Resources:
  InputBucket:
    Condition: ShouldCreateInputBucket
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: StorageClassAndRetention
            Status: Enabled
            ExpirationInDays:
              Ref: RetentionDays
            Transitions:
              - TransitionInDays: 1
                StorageClass: INTELLIGENT_TIERING
  OutputBucket:
    Condition: ShouldCreateOutputBucket
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: LifecycleRule
            Status: Enabled
            ExpirationInDays:
              Ref: RetentionDays
            Transitions:
              - TransitionInDays: 1
                StorageClass: INTELLIGENT_TIERING
        # SSM:
        #   Type: AWS::CloudFormation::Stack
        #   Properties:
        #     TemplateURL: https://raw.githubusercontent.com/luis95garay/speech2text_sentimentanalysis/main/stacks/myssm.yaml
        #     Parameters:
        # BulkUploadBucketName:
        #   Fn::If:
        #     - ShouldCreateBulkUploadBucket
        #     - Ref: BulkUploadBucket
        #     - Ref: BulkUploadBucketName
        # BulkUploadMaxDripRate:
        #   Ref: BulkUploadMaxDripRate
        # BulkUploadMaxTranscribeJobs:
        #   Ref: BulkUploadMaxTranscribeJobs
        # ComprehendLanguages:
        #   Ref: ComprehendLanguages
        # ContentRedactionLanguages:
        #   Ref: ContentRedactionLanguages
        # ConversationLocation:
        #   Ref: ConversationLocation
        # EntityRecognizerEndpoint:
        #   Ref: EntityRecognizerEndpoint
        # EntityStringMap:
        #   Ref: EntityStringMap
        # EntityThreshold:
        #   Ref: EntityThreshold
        # EntityTypes:
        #   Ref: EntityTypes
        # InputBucketAudioPlayback:
        #   Ref: InputBucketAudioPlayback
        # InputBucketFailedTranscriptions:
        #   Ref: InputBucketFailedTranscriptions
        # InputBucketName:
        #   Fn::If:
        #     - ShouldCreateInputBucket
        #     - Ref: InputBucket
        #     - Ref: InputBucketName
        # InputBucketRawAudio:
        #   Ref: InputBucketRawAudio
        # InputBucketOrigTranscripts:
        #   Ref: InputBucketOrigTranscripts
        # MaxSpeakers:
        #   Ref: MaxSpeakers
        # MinSentimentNegative:
        #   Ref: MinSentimentNegative
        # MinSentimentPositive:
        #   Ref: MinSentimentPositive
        # OutputBucketName:
        #   Fn::If:
        #     - ShouldCreateOutputBucket
        #     - Ref: OutputBucket
        #     - Ref: OutputBucketName
        # OutputBucketTranscribeResults:
        #   Ref: OutputBucketTranscribeResults
        # OutputBucketParsedResults:
        #   Ref: OutputBucketParsedResults
        # SpeakerNames:
        #   Ref: SpeakerNames
        # SpeakerSeparationType:
        #   Ref: SpeakerSeparationType
        # StepFunctionName:
        #   Ref: StepFunctionName
        # BulkUploadStepFunctionName:
        #   Ref: BulkUploadStepFunctionName
        # SupportFilesBucketName:
        #   Fn::If:
        #     - ShouldCreateSupportFilesBucket
        #     - Ref: SupportFilesBucket
        #     - Ref: SupportFilesBucketName
        # TranscribeLanguages:
        #   Ref: TranscribeLanguages
        # TranscribeApiMode:
        #   Ref: TranscribeApiMode
        # TelephonyCTRType:
        #   Ref: TelephonyCTRType
        # TelephonyCTRFileSuffix:
        #   Ref: TelephonyCTRFileSuffix
        # CallRedactionTranscript:
        #   Ref: CallRedactionTranscript
        # CallRedactionAudio:
        #   Ref: CallRedactionAudio
        # VocabFilterName:
        #   Ref: VocabFilterName
        # VocabFilterMode:
        #   Ref: VocabFilterMode
        # VocabularyName:
        #   Ref: VocabularyName
        # CustomLangModelName:
        #   Ref: CustomLangModelName
        # FilenameDatetimeRegex:
        #   Ref: FilenameDatetimeRegex
        # FilenameDatetimeFieldMap:
        #   Ref: FilenameDatetimeFieldMap
        # FilenameGUIDRegex:
        #   Ref: FilenameGUIDRegex
        # FilenameAgentRegex:
        #   Ref: FilenameAgentRegex
        # FilenameCustRegex:
        #   Ref: FilenameCustRegex
        # KendraIndexId:
        #   Fn::If:
        #     - ShouldEnableKendraSearch
        #     - Ref: KendraIndex
        #     - None
        DatabaseName:
          Ref: DatabaseName
Outputs:
  InputBucket:
    Description: S3 Bucket for uploading input audio files
    Value:
      Fn::If:
        - ShouldCreateInputBucket
        - Ref: InputBucket
        - Ref: InputBucketName
  OutputBucket:
    Description: S3 Bucket where Transcribe output files are delivered
    Value:
      Fn::If:
        - ShouldCreateOutputBucket
        - Ref: OutputBucket
        - Ref: OutputBucketName
