AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon Transcribe Post Call Analytics - PCA Server
Parameters:
  ffmpegDownloadUrl:
    Type: String
    Default: http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
    Description: URL for ffmpeg binary distribution tar file download - see https://www.johnvansickle.com/ffmpeg/
  # CallSummarization:
  #   Default: DISABLED
  #   Type: String
  #   AllowedValues:
  #   - DISABLED
  #   - SAGEMAKER
  #   - BEDROCK
  #   - LAMBDA
  #   - ANTHROPIC
  #   Description: "Set to enable call summarization by a Large Language Model. The\
  #     \ SAGEMAKER option uses a SageMaker endpoint with the pretrained bart-large-cnn-samsum\
  #     \ model with a ml.m5.xlarge instance type.  The LAMBDA option requires you \
  #     \ to provide a function ARN below. The ANTHROPIC option is a third party service,\
  #     \ and you must enter your Anthropic API key below.\n"
  # SummarizationBedrockModelId:
  #   Type: String
  #   Default: anthropic.claude-instant-v1
  #   AllowedValues:
  #   - amazon.titan-text-express-v1
  #   - anthropic.claude-v1
  #   - anthropic.claude-instant-v1
  #   - anthropic.claude-v2
  #   Description: (Optional) If 'CallSummarization' is BEDROCK, which Bedrock model
  #     to use.
  # SummarizationSageMakerInitialInstanceCount:
  #   Type: Number
  #   MinValue: 0
  #   Default: 1
  #   Description: "(Optional) If 'CallSummarization' is SAGEMAKER, provide initial\
  #     \ instance count. Set to '0' to enable Serverless Inference (for cold-start\
  #     \ delay tolerant deployments only).\n"
  # SummarizationLLMThirdPartyApiKey:
  #   Type: String
  #   Description: "Secrets manager secret Arn containing the third party LLM API key\n"
  #   Default: ''
  # SummarizationLambdaFunctionArn:
  #   Default: ''
  #   Type: String
  #   AllowedPattern: ^(|arn:aws:lambda:.*)$
  #   Description: "(Optional) If 'CallSummarization' is LAMBDA, provide ARN for a Lambda\
  #     \ function. \n"
  Boto3LayerArn:
    Default: ""
    Type: String
    Description:
      External Boto3 Layer Arn to use. If none is provided, one will be
      created automatically via boto3.template
  PyUtilsLayerArn:
    Type: String
    Description: PyUtils layer arn from main stack.
Conditions:
  ShouldCreateBoto3Layer:
    Fn::Equals:
      - Ref: Boto3LayerArn
      - ""
#   ShouldDeployBedrockSummarizer:
#     Fn::Equals:
#       - Ref: CallSummarization
#       - BEDROCK
#   ShouldDeploySageMakerSummarizer:
#     Fn::Equals:
#       - Ref: CallSummarization
#       - SAGEMAKER
#   ShouldEnableAnthropicSummarizer:
#     Fn::Equals:
#       - Ref: CallSummarization
#       - ANTHROPIC
#   ShouldEnableEndOfCallLambdaHookFunction:
#     Fn::Equals:
#       - Ref: CallSummarization
#       - LAMBDA
#   IsTranscriptSummaryEnabled:
#     Fn::Or:
#       - Condition: ShouldDeployBedrockSummarizer
#       - Condition: ShouldEnableEndOfCallLambdaHookFunction
#       - Condition: ShouldDeploySageMakerSummarizer
#       - Condition: ShouldEnableAnthropicSummarizer
Resources:
  FFMPEG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://asistente-virtual-no-one.s3.amazonaws.com/FFMPEG_download.yaml
      Parameters:
        ffmpegDownloadUrl:
          Ref: ffmpegDownloadUrl
  BOTO3:
    Condition: ShouldCreateBoto3Layer
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://asistente-virtual-no-one.s3.amazonaws.com/boto3.yaml
  DDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://asistente-virtual-no-one.s3.amazonaws.com/DDBTable.yaml
  PCA:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://asistente-virtual-no-one.s3.amazonaws.com/state_machine.yaml
      Parameters:
        TableName:
          Fn::GetAtt:
            - DDB
            - Outputs.TableName
        FFMPEGZipName:
          Fn::GetAtt:
            - FFMPEG
            - Outputs.FFMPEGZipName
        Boto3Layer:
          Fn::If:
            - ShouldCreateBoto3Layer
            - Fn::GetAtt:
                - BOTO3
                - Outputs.Boto3Layer
            - Ref: Boto3LayerArn
        PyUtilsLayer:
          Ref: PyUtilsLayerArn
        # CallSummarization:
        #   Ref: CallSummarization
        # SummarizationBedrockModelId:
        #   Ref: SummarizationBedrockModelId
        # SummarizationSagemakerEndpointName:
        #   Fn::If:
        #     - ShouldDeploySageMakerSummarizer
        #     - Fn::GetAtt:
        #         - SageMakerTranscriptSummaryStack
        #         - Outputs.EndpointName
        #     - ""
        # SummarizationSagemakerEndpointArn:
        #   Fn::If:
        #     - ShouldDeploySageMakerSummarizer
        #     - Fn::GetAtt:
        #         - SageMakerTranscriptSummaryStack
        #         - Outputs.EndpointArn
        #     - ""
        # SummarizationLLMThirdPartyApiKey:
        #   Ref: SummarizationLLMThirdPartyApiKey
        # SummarizationLambdaFunctionArn:
        #   Ref: SummarizationLambdaFunctionArn
  Trigger:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://asistente-virtual-no-one.s3.amazonaws.com/s3trigger.yaml
      Parameters:
        TableName:
          Fn::GetAtt:
            - DDB
            - Outputs.TableName
        Boto3Layer:
          Fn::If:
            - ShouldCreateBoto3Layer
            - Fn::GetAtt:
                - BOTO3
                - Outputs.Boto3Layer
            - Ref: Boto3LayerArn
        PyUtilsLayer:
          Ref: PyUtilsLayerArn
        # Summarize:
        #   Fn::If:
        #     - IsTranscriptSummaryEnabled
        #     - "true"
        #     - "false"
  # BulkImport:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://s3.us-east-1.amazonaws.com/aws-ml-blog-us-east-1/artifacts/pca/0.7.4/b9f8df4d17407359ad5817b15cf5c759.template
  # GlueDatabase:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://s3.us-east-1.amazonaws.com/aws-ml-blog-us-east-1/artifacts/pca/0.7.4/0f8e311d7cd8f49750b87cd1cac499ed.template
  # SageMakerTranscriptSummaryStack:
  #   Type: AWS::CloudFormation::Stack
  #   Condition: ShouldDeploySageMakerSummarizer
  #   Properties:
  #     TemplateURL: https://s3.us-east-1.amazonaws.com/aws-ml-blog-us-east-1/artifacts/pca/0.7.4/9d740a729393d85c6ff7b6b4fb27b7f5.template
  #     Parameters:
  #       InitialInstanceCount:
  #         Ref: SummarizationSageMakerInitialInstanceCount
Outputs:
  FetchTranscriptArn:
    Value:
      Fn::GetAtt:
        - PCA
        - Outputs.FetchTranscriptArn
  # SummarizerArn:
  #   Value:
  #     Fn::GetAtt:
  #       - PCA
  #       - Outputs.SummarizerArn
  RolesForKMSKey:
    Value:
      Fn::Join:
        - ", "
        - - Fn::Sub: ${Trigger.Outputs.RolesForKMSKey}
          - Fn::Sub: ${PCA.Outputs.RolesForKMSKey}
          # - Fn::Sub: ${BulkImport.Outputs.RolesForKMSKey}
